config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  devise_for :users, skip: %i[registrations], controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete 'users' => 'devise/registrations#destroy', as: :user_registration
  end

  namespace :auth do
    resource :profile, only: %i[edit update]
    resources :works, only: %i[index edit update] do
      collection do
        post 'import'
      end
    end
  end

  resources :users, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  mount_uploader :avatar, ProfileAvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable,
         :validatable, :omniauthable, omniauth_providers: %i[github]

  has_one :profile, dependent: :destroy
  has_many :works, dependent: :destroy
  has_many :published_works, -> { published }, class_name: 'Work'

  delegate :name, :pr, :pr?, :avatar, :avatar?, to: :profile

  def self.find_or_create_user!(auth)
    user = find_by(provider: auth.provider, uid: auth.uid) || build_user_by_auth(auth)
    user.assign_attributes(access_token: auth.dig(:credentials, :token))
    user.save!
    user
  end

  def self.build_user_by_auth(auth)
    User.new do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.build_profile_by_auth(auth)
    end
  end

  private_class_method :build_user_by_auth

  def import_works_from_github
    Work.transaction do
      works.destroy_not_included_repos!(github_account.repositories)
      github_account.repositories.each do |repository|
        work = works.find_or_initialize_by(repository_id: repository.id)
        work.assign_attributes_by_repos(repository)
        work.save!
      end
    end
  end

  def build_profile_by_auth(auth)
    profile = build_profile
    profile.name = auth.info.name
    profile.pr = auth.extra.raw_info.bio
    profile.remote_avatar_url = auth.info.image
  end

  private

  def github_account
    @github_account ||= GithubAccount.new(self)
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user

  mount_uploader :image, WorkImageUploader
  delegate :profile, to: :user
  delegate :name, to: :profile, prefix: true

  scope :published, -> { where(published: true) }

  def self.destroy_not_included_repos!(repositories)
    works = where.not(repository_id: repositories.map(&:id))
    works.destroy_all
    raise '作品を削除できませんでした。' unless works.all?(&:destroyed?)
  end

  def assign_attributes_by_repos(repository)
    # 初めてgithubリポジトリを取得する時のみリポジトリ名や説明文を反映する（あとでアプリ内で修正可能なため）
    assign_attributes(name: repository.name, description: repository.description) if new_record?
    assign_attributes(language: repository.language,
                      svn_url: repository.svn_url,
                      stargazers: repository.stargazers_count,
                      forks: repository.forks_count,
                      pushed_at: repository.pushed_at,
                      watchers: repository.watchers)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.find_or_create_user!(request.env["omniauth.auth"])
    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: "Github")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  USERS_LIMIT = 24
  WORKS_LIMIT = 60

  def index
    @users = User.order(id: :desc).limit(USERS_LIMIT)
    @works = Work.includes(user: :profile).published.order(pushed_at: :desc).limit(WORKS_LIMIT)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/application/_flash.html.haml
- unless flash.empty?
  #flash
    - if notice
      .alert.alert-success{role: 'alert','data-test': 'flash__success'}
        = notice
    - if alert
      .alert.alert-danger{role: 'alert','data-test': 'flash__failure'}
        = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GitHubハブ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #wrapper
      %header#header
        #header-logo
          = link_to 'GitHubハブ', root_path
        %ul#header-nav
          - if user_signed_in?
            %li= link_to '作品一覧', auth_works_path
            %li= link_to '公開ページ', user_path(current_user)
            %li= link_to 'プロフィール編集', edit_auth_profile_path
            %li= link_to '退会', user_registration_path, method: :delete, data: {confirm: '本当に退会しますか？'}
            %li= link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'ログイン', new_user_session_path
      #container.mt-5
        = render 'application/flash'
        = yield

app/views/profiles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@profile) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :pr
    = f.association :user

  .form-actions
    = f.button :submit

app/views/users/_user.html.haml
%li.users__card
  %p.users__img
    = link_to user_path(user) do
      = image_tag user.avatar.url if user.avatar?
      = image_tag 'no_image.png' unless user.avatar?
  %div.users__detail
    = link_to user_path(user) do
      %p.strong= user.name
    %p= user.pr if user.pr?

app/views/users/index.html.haml
- unless user_signed_in?
  %p GitHubのアカウントがあればポートフォリオサイトが簡単に作れます。
  %p.mt-5.mb-5= link_to 'ご利用はこちら', new_user_session_path, class: 'btn btn-primary'

- if @users.present?
  %h1 登録ユーザー一覧
  %ul.users
    = render @users

- if @works.present?
  %h2.mt-5 登録作品一覧
  %ul.works
    = render @works

app/views/users/show.html.haml
%h1= "作者：#{@user.name}"

.profile.mt-5
  .profile__thumb
    = image_tag @user.avatar.url if @user.avatar?
    = image_tag 'no_image.png' unless @user.avatar?
  .profile__pr= simple_format(@user.pr)

%ul.works
  = render @user.published_works.includes(:user)

app/views/works/_work.html.haml
%li.works__card
  %p.works__img
    = link_to work.svn_url do
      = image_tag work.image.thumb.url if work.image?
      = image_tag 'no_image.png' unless work.image?
  %div.works__detail
    = link_to work.svn_url do
      %p.strong= work.name
    %p.badge.badge-info= work.language if work.language?
    %p.badge.badge-warning= "★ #{work.stargazers}"
    %p= "作者：#{work.profile_name}"
    %p= work.description if work.description?